language: node_js
services:
  - docker
sudo: false
node_js: 
  - "node"
cache:
  directories:
    - ~/.npm
    - ~/.cache
stages:
  - name: unit-tests
  - name: deploy
jobs:
  include:
    - stage: unit-tests
      script: bash ./ci/unit-tests
    - stage: deploy
      script: bash ./ci/deploy && bash ./ci/release
